// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASudOA1jqlOjbPQ_8tfjTwEf74bmGlrBM',
    appId: '1:102984828092:web:a55b727251316906a3bcb9',
    messagingSenderId: '102984828092',
    projectId: 'spring-firefly-438711-j3',
    authDomain: 'spring-firefly-438711-j3.firebaseapp.com',
    storageBucket: 'spring-firefly-438711-j3.firebasestorage.app',
    measurementId: 'G-V2TRM41KE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oLPTx885oPFMMZsF5AHU4QdAyc2Sawc',
    appId: '1:102984828092:android:a864cb331fa322b9a3bcb9',
    messagingSenderId: '102984828092',
    projectId: 'spring-firefly-438711-j3',
    storageBucket: 'spring-firefly-438711-j3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsk1mLzFP4gbe3UT0AwM2xMOkoADD6K5g',
    appId: '1:102984828092:ios:d45776291134e50ca3bcb9',
    messagingSenderId: '102984828092',
    projectId: 'spring-firefly-438711-j3',
    storageBucket: 'spring-firefly-438711-j3.firebasestorage.app',
    iosBundleId: 'com.umbrella.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsk1mLzFP4gbe3UT0AwM2xMOkoADD6K5g',
    appId: '1:102984828092:ios:d45776291134e50ca3bcb9',
    messagingSenderId: '102984828092',
    projectId: 'spring-firefly-438711-j3',
    storageBucket: 'spring-firefly-438711-j3.firebasestorage.app',
    iosBundleId: 'com.umbrella.chattingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASudOA1jqlOjbPQ_8tfjTwEf74bmGlrBM',
    appId: '1:102984828092:web:c72b1078839a05daa3bcb9',
    messagingSenderId: '102984828092',
    projectId: 'spring-firefly-438711-j3',
    authDomain: 'spring-firefly-438711-j3.firebaseapp.com',
    storageBucket: 'spring-firefly-438711-j3.firebasestorage.app',
    measurementId: 'G-KP6MKKP01M',
  );
}
